#!/usr/bin/env node
// Generates human-readable index/matrix files from the registry (Section 40).
// Output is written to shared/registry/generated/ and is regenerated by
// this script — it is not hand-edited. See lib/build-index-markdown.mjs
// for the actual generation logic (shared with validate-registry.mjs's
// generated-output-drift check).

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { buildIndexMarkdown } from './lib/build-index-markdown.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..', '..');
const OUT_PATH = path.join(ROOT, 'shared', 'registry', 'generated', 'REGISTRY-INDEX.md');

writeFileSync(OUT_PATH, buildIndexMarkdown(ROOT));
console.log(`Wrote ${path.join('shared', 'registry', 'generated', 'REGISTRY-INDEX.md')}`);
