#!/usr/bin/env node
// Generates human-readable index/matrix files from the registry (Section 40).
// Output is written to shared/registry/generated/ and is regenerated by
// this script — it is not hand-edited.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import yaml from 'js-yaml';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..', '..');
const OUT_DIR = path.join(ROOT, 'shared', 'registry', 'generated');

function loadYaml(relPath) {
  const full = path.join(ROOT, relPath);
  if (!existsSync(full)) return null;
  return yaml.load(readFileSync(full, 'utf8'));
}

const competencyState = loadYaml('01-SALIM-BURAK-DIGITAL-TWIN/registry/competency-state.yaml');
const domainsCatalog = loadYaml('shared/registry/catalog/domains.yaml');
const labsCatalog = loadYaml('shared/registry/catalog/labs.yaml');
const evidence = loadYaml('06-EVIDENCE/evidence.yaml');
const relationships = loadYaml('shared/registry/relationships/relationships.yaml');

const lines = [];
lines.push('<!-- GENERATED by scripts/registry/build-indexes.mjs — do not hand-edit. -->');
lines.push('# Registry-Generated Index');
lines.push('');
lines.push(`Generated from ${['competency-state.yaml', 'domains.yaml', 'labs.yaml', 'evidence.yaml', 'relationships.yaml'].join(', ')} at build time.`);
lines.push('');

lines.push('## Competency Matrix (knowledge / professional / repository)');
lines.push('');
lines.push('| Competency | Knowledge | Professional | Repository |');
lines.push('|---|---|---|---|');
for (const c of competencyState.competencies) {
  const prof = c.professional.status || Object.entries(c.professional).map(([k, v]) => `${k}:${v}`).join(', ');
  lines.push(`| ${c.label} | ${c.knowledge} | ${prof} | ${c.repository.status} |`);
}
lines.push('');

lines.push('## Domain Maturity');
lines.push('');
lines.push('| Domain | Exposure | Note |');
lines.push('|---|---|---|');
for (const d of domainsCatalog.items) {
  lines.push(`| ${d.label} | ${d.exposure} | ${d.note || ''} |`);
}
lines.push('');

lines.push('## Executable Labs');
lines.push('');
lines.push('| Lab | Maturity | Path |');
lines.push('|---|---|---|');
for (const l of labsCatalog.items) {
  lines.push(`| ${l.label} | ${l.maturity} | \`${l.path}\` |`);
}
lines.push('');

lines.push('## Evidence');
lines.push('');
lines.push('| Evidence | Maturity | Artifact |');
lines.push('|---|---|---|');
for (const e of evidence.items) {
  lines.push(`| ${e.label} | ${e.maturity} | \`${e.artifact}\` |`);
}
lines.push('');

lines.push(`## Relationships (${relationships.relationships.length} edges)`);
lines.push('');
lines.push('| From | Predicate | To |');
lines.push('|---|---|---|');
for (const r of relationships.relationships) {
  lines.push(`| ${r.from} | ${r.predicate} | ${r.to} |`);
}
lines.push('');

writeFileSync(path.join(OUT_DIR, 'REGISTRY-INDEX.md'), lines.join('\n') + '\n');
console.log(`Wrote ${path.join('shared', 'registry', 'generated', 'REGISTRY-INDEX.md')}`);
